pages:
  image:
    name: registry.roqs.basf.net/base-images/python
    docker:
      user: "0:0"

  script:
    - apt update
    - apt install -y git pandoc
    - pip install poetry
    - poetry install
    - cd examples
    - poetry run dvc remote modify origin endpointurl $AWS_ENDPOINT_URL
    - poetry run dvc pull --allow-missing
    - cd docs
    - poetry run sphinx-build -M html source build/
    - cd ..
    - mkdir -p "public"
    - cp -r docs/build/html/* public/
  artifacts:
    paths:
      - public
