initialize_BuildASEslab:
  a: null
  c: false
  crystal: fcc111
  orthogonal: true
  periodic: true
  size:
  - 3
  - 4
  - 4
  symbol: Cu
  vacuum: 10
initialize_RelaxAdsorptionConfigs:
  adsorbate_id: -1
  fmax: 0.05
  height: 2.1
  model:
    _cls: mlipx.nodes.generic_ase.GenericASECalculator
    class_name: mace_mp
    device: auto
    kwargs:
      model: medium
    module: mace.calculators
  mol_index: 0
  optimizer: LBFGS
  position: all
  slab_id: -1
  steps: 300
initialize_Smiles2Conformers:
  max_attempts: 1000
  num_confs: 1
  random_seed: 42
  smiles: CO
