7net_StructureOptimization:
  data_id: -1
  fmax: 0.1
  model:
    _cls: mlipx.nodes.generic_ase.GenericASECalculator
    class_name: SevenNetCalculator
    device: auto
    kwargs:
      model: 7net-0
    module: sevenn.sevennet_calculator
  optimizer: LBFGS
  steps: 100000000
initialize_Smiles2Conformers:
  max_attempts: 1000
  num_confs: 100
  random_seed: 42
  smiles: C12C3C1C4C2C34
mace_agne_StructureOptimization:
  data_id: -1
  fmax: 0.1
  model:
    _cls: mlipx.nodes.generic_ase.GenericASECalculator
    class_name: MACECalculator
    device: auto
    kwargs:
      model_paths: ../models/mace_agnesi.model
    module: mace.calculators
  optimizer: LBFGS
  steps: 100000000
mace_medm_StructureOptimization:
  data_id: -1
  fmax: 0.1
  model:
    _cls: mlipx.nodes.generic_ase.GenericASECalculator
    class_name: MACECalculator
    device: auto
    kwargs:
      model_paths: ../models/mace_medium.model
    module: mace.calculators
  optimizer: LBFGS
  steps: 100000000
