7net_PhaseDiagram:
  chemsys: null
  data_ids: null
  fmax: 0.05
  geo_opt: false
  model:
    _cls: mlipx.nodes.generic_ase.GenericASECalculator
    class_name: SevenNetCalculator
    device: auto
    kwargs:
      model: 7net-0
    module: sevenn.sevennet_calculator
Orb_d3_sm_v2_PhaseDiagram:
  chemsys: null
  data_ids: null
  fmax: 0.05
  geo_opt: false
  model:
    _cls: models.OrbCalc
    name: orb_d3_sm_v2
Orb_d3_v2_PhaseDiagram:
  chemsys: null
  data_ids: null
  fmax: 0.05
  geo_opt: false
  model:
    _cls: models.OrbCalc
    name: orb_d3_v2
Orb_d3_xs_v2_PhaseDiagram:
  chemsys: null
  data_ids: null
  fmax: 0.05
  geo_opt: false
  model:
    _cls: models.OrbCalc
    name: orb_d3_xs_v2
Orb_mptraj_v2_PhaseDiagram:
  chemsys: null
  data_ids: null
  fmax: 0.05
  geo_opt: false
  model:
    _cls: models.OrbCalc
    name: orb_mptraj_only_v2
Orb_v2_PhaseDiagram:
  chemsys: null
  data_ids: null
  fmax: 0.05
  geo_opt: false
  model:
    _cls: models.OrbCalc
    name: orb_v2
initialize_LoadDataFile:
  start: 0
  step: 1
  stop: null
mace_agnesi_PhaseDiagram:
  chemsys: null
  data_ids: null
  fmax: 0.05
  geo_opt: false
  model:
    _cls: mlipx.nodes.generic_ase.GenericASECalculator
    class_name: MACECalculator
    device: cpu
    kwargs:
      dtype: float64
      model_paths: ../models/mace_agnesi.model
    module: mace.calculators
mace_medium_PhaseDiagram:
  chemsys: null
  data_ids: null
  fmax: 0.05
  geo_opt: false
  model:
    _cls: mlipx.nodes.generic_ase.GenericASECalculator
    class_name: MACECalculator
    device: cpu
    kwargs:
      dtype: float64
      model_paths: ../models/mace_medium.model
    module: mace.calculators
