7net_diatomics_HomonuclearDiatomics:
  elements: &id001
  - O
  - Cu
  eq_distance: covalent-radiuis
  max_distance: 2.0
  min_distance: 0.5
  model:
    _cls: mlipx.nodes.generic_ase.GenericASECalculator
    class_name: SevenNetCalculator
    device: auto
    kwargs:
      model: 7net-0
    module: sevenn.sevennet_calculator
  n_points: 100
7net_ev_0_EnergyVolumeCurve:
  data_id: 0
  model:
    _cls: mlipx.nodes.generic_ase.GenericASECalculator
    class_name: SevenNetCalculator
    device: auto
    kwargs:
      model: 7net-0
    module: sevenn.sevennet_calculator
  n_points: 50
  start: 0.75
  stop: 2.0
7net_md_0_MolecularDynamics:
  data_id: 0
  model:
    _cls: mlipx.nodes.generic_ase.GenericASECalculator
    class_name: SevenNetCalculator
    device: auto
    kwargs:
      model: 7net-0
    module: sevenn.sevennet_calculator
  modifiers:
  - _cls: mlipx.nodes.modifier.TemperatureRampModifier
    end_temperature: 400
    interval: 1
    start_temperature: null
    total_steps: 100
  observers:
  - _cls: mlipx.nodes.observer.MaximumForceObserver
    f_max: 100
  steps: 100
  thermostat:
    _cls: mlipx.nodes.molecular_dynamics.LangevinConfig
    friction: 0.05
    temperature: 300
    timestep: 0.5
7net_struct_optim_0_StructureOptimization:
  data_id: 0
  fmax: 0.1
  model:
    _cls: mlipx.nodes.generic_ase.GenericASECalculator
    class_name: SevenNetCalculator
    device: auto
    kwargs:
      model: 7net-0
    module: sevenn.sevennet_calculator
  optimizer: LBFGS
  steps: 100000000
mace_agne_diatomics_HomonuclearDiatomics:
  elements: *id001
  eq_distance: covalent-radiuis
  max_distance: 2.0
  min_distance: 0.5
  model:
    _cls: mlipx.nodes.generic_ase.GenericASECalculator
    class_name: MACECalculator
    device: auto
    kwargs:
      model_paths: ../models/mace_agnesi.model
    module: mace.calculators
  n_points: 100
mace_agne_ev_0_EnergyVolumeCurve:
  data_id: 0
  model:
    _cls: mlipx.nodes.generic_ase.GenericASECalculator
    class_name: MACECalculator
    device: auto
    kwargs:
      model_paths: ../models/mace_agnesi.model
    module: mace.calculators
  n_points: 50
  start: 0.75
  stop: 2.0
mace_agne_md_0_MolecularDynamics:
  data_id: 0
  model:
    _cls: mlipx.nodes.generic_ase.GenericASECalculator
    class_name: MACECalculator
    device: auto
    kwargs:
      model_paths: ../models/mace_agnesi.model
    module: mace.calculators
  modifiers:
  - _cls: mlipx.nodes.modifier.TemperatureRampModifier
    end_temperature: 400
    interval: 1
    start_temperature: null
    total_steps: 100
  observers:
  - _cls: mlipx.nodes.observer.MaximumForceObserver
    f_max: 100
  steps: 100
  thermostat:
    _cls: mlipx.nodes.molecular_dynamics.LangevinConfig
    friction: 0.05
    temperature: 300
    timestep: 0.5
mace_agne_struct_optim_0_StructureOptimization:
  data_id: 0
  fmax: 0.1
  model:
    _cls: mlipx.nodes.generic_ase.GenericASECalculator
    class_name: MACECalculator
    device: auto
    kwargs:
      model_paths: ../models/mace_agnesi.model
    module: mace.calculators
  optimizer: LBFGS
  steps: 100000000
mace_medm_diatomics_HomonuclearDiatomics:
  elements: *id001
  eq_distance: covalent-radiuis
  max_distance: 2.0
  min_distance: 0.5
  model:
    _cls: mlipx.nodes.generic_ase.GenericASECalculator
    class_name: MACECalculator
    device: auto
    kwargs:
      model_paths: ../models/mace_medium.model
    module: mace.calculators
  n_points: 100
mace_medm_ev_0_EnergyVolumeCurve:
  data_id: 0
  model:
    _cls: mlipx.nodes.generic_ase.GenericASECalculator
    class_name: MACECalculator
    device: auto
    kwargs:
      model_paths: ../models/mace_medium.model
    module: mace.calculators
  n_points: 50
  start: 0.75
  stop: 2.0
mace_medm_md_0_MolecularDynamics:
  data_id: 0
  model:
    _cls: mlipx.nodes.generic_ase.GenericASECalculator
    class_name: MACECalculator
    device: auto
    kwargs:
      model_paths: ../models/mace_medium.model
    module: mace.calculators
  modifiers:
  - _cls: mlipx.nodes.modifier.TemperatureRampModifier
    end_temperature: 400
    interval: 1
    start_temperature: null
    total_steps: 100
  observers:
  - _cls: mlipx.nodes.observer.MaximumForceObserver
    f_max: 100
  steps: 100
  thermostat:
    _cls: mlipx.nodes.molecular_dynamics.LangevinConfig
    friction: 0.05
    temperature: 300
    timestep: 0.5
mace_medm_struct_optim_0_StructureOptimization:
  data_id: 0
  fmax: 0.1
  model:
    _cls: mlipx.nodes.generic_ase.GenericASECalculator
    class_name: MACECalculator
    device: auto
    kwargs:
      model_paths: ../models/mace_medium.model
    module: mace.calculators
  optimizer: LBFGS
  steps: 100000000
mptraj_LoadDataFile:
  start: 0
  step: 1
  stop: null
rattle_Rattle:
  seed: 42
  stdev: 0.01
