FilterAtoms:
  elements:
  - B
  - F
  filtering_type: exclusive
LoadDataFile:
  start: 0
  step: 1
  stop: null
frame_0_7net_EnergyVolumeCurve:
  data_id: 0
  model:
    _cls: mlipx.nodes.generic_ase.GenericASECalculator
    class_name: SevenNetCalculator
    device: auto
    kwargs:
      model: 7net-0
    module: sevenn.sevennet_calculator
  n_points: 50
  start: 0.75
  stop: 2.0
frame_0_mace_agne_EnergyVolumeCurve:
  data_id: 0
  model:
    _cls: mlipx.nodes.generic_ase.GenericASECalculator
    class_name: MACECalculator
    device: auto
    kwargs:
      model_paths: ../models/mace_agnesi.model
    module: mace.calculators
  n_points: 50
  start: 0.75
  stop: 2.0
frame_0_mace_medm_EnergyVolumeCurve:
  data_id: 0
  model:
    _cls: mlipx.nodes.generic_ase.GenericASECalculator
    class_name: MACECalculator
    device: auto
    kwargs:
      model_paths: ../models/mace_medium.model
    module: mace.calculators
  n_points: 50
  start: 0.75
  stop: 2.0
frame_1_7net_EnergyVolumeCurve:
  data_id: 1
  model:
    _cls: mlipx.nodes.generic_ase.GenericASECalculator
    class_name: SevenNetCalculator
    device: auto
    kwargs:
      model: 7net-0
    module: sevenn.sevennet_calculator
  n_points: 50
  start: 0.75
  stop: 2.0
frame_1_mace_agne_EnergyVolumeCurve:
  data_id: 1
  model:
    _cls: mlipx.nodes.generic_ase.GenericASECalculator
    class_name: MACECalculator
    device: auto
    kwargs:
      model_paths: ../models/mace_agnesi.model
    module: mace.calculators
  n_points: 50
  start: 0.75
  stop: 2.0
frame_1_mace_medm_EnergyVolumeCurve:
  data_id: 1
  model:
    _cls: mlipx.nodes.generic_ase.GenericASECalculator
    class_name: MACECalculator
    device: auto
    kwargs:
      model_paths: ../models/mace_medium.model
    module: mace.calculators
  n_points: 50
  start: 0.75
  stop: 2.0
frame_2_7net_EnergyVolumeCurve:
  data_id: 2
  model:
    _cls: mlipx.nodes.generic_ase.GenericASECalculator
    class_name: SevenNetCalculator
    device: auto
    kwargs:
      model: 7net-0
    module: sevenn.sevennet_calculator
  n_points: 50
  start: 0.75
  stop: 2.0
frame_2_mace_agne_EnergyVolumeCurve:
  data_id: 2
  model:
    _cls: mlipx.nodes.generic_ase.GenericASECalculator
    class_name: MACECalculator
    device: auto
    kwargs:
      model_paths: ../models/mace_agnesi.model
    module: mace.calculators
  n_points: 50
  start: 0.75
  stop: 2.0
frame_2_mace_medm_EnergyVolumeCurve:
  data_id: 2
  model:
    _cls: mlipx.nodes.generic_ase.GenericASECalculator
    class_name: MACECalculator
    device: auto
    kwargs:
      model_paths: ../models/mace_medium.model
    module: mace.calculators
  n_points: 50
  start: 0.75
  stop: 2.0
frame_3_7net_EnergyVolumeCurve:
  data_id: 3
  model:
    _cls: mlipx.nodes.generic_ase.GenericASECalculator
    class_name: SevenNetCalculator
    device: auto
    kwargs:
      model: 7net-0
    module: sevenn.sevennet_calculator
  n_points: 50
  start: 0.75
  stop: 2.0
frame_3_mace_agne_EnergyVolumeCurve:
  data_id: 3
  model:
    _cls: mlipx.nodes.generic_ase.GenericASECalculator
    class_name: MACECalculator
    device: auto
    kwargs:
      model_paths: ../models/mace_agnesi.model
    module: mace.calculators
  n_points: 50
  start: 0.75
  stop: 2.0
frame_3_mace_medm_EnergyVolumeCurve:
  data_id: 3
  model:
    _cls: mlipx.nodes.generic_ase.GenericASECalculator
    class_name: MACECalculator
    device: auto
    kwargs:
      model_paths: ../models/mace_medium.model
    module: mace.calculators
  n_points: 50
  start: 0.75
  stop: 2.0
frame_4_7net_EnergyVolumeCurve:
  data_id: 4
  model:
    _cls: mlipx.nodes.generic_ase.GenericASECalculator
    class_name: SevenNetCalculator
    device: auto
    kwargs:
      model: 7net-0
    module: sevenn.sevennet_calculator
  n_points: 50
  start: 0.75
  stop: 2.0
frame_4_mace_agne_EnergyVolumeCurve:
  data_id: 4
  model:
    _cls: mlipx.nodes.generic_ase.GenericASECalculator
    class_name: MACECalculator
    device: auto
    kwargs:
      model_paths: ../models/mace_agnesi.model
    module: mace.calculators
  n_points: 50
  start: 0.75
  stop: 2.0
frame_4_mace_medm_EnergyVolumeCurve:
  data_id: 4
  model:
    _cls: mlipx.nodes.generic_ase.GenericASECalculator
    class_name: MACECalculator
    device: auto
    kwargs:
      model_paths: ../models/mace_medium.model
    module: mace.calculators
  n_points: 50
  start: 0.75
  stop: 2.0
