stages:
  initialize_MPRester:
    cmd: zntrack run mlipx.nodes.mp_api.MPRester --name initialize_MPRester
    metrics:
    - nodes/initialize/MPRester/node-meta.json:
        cache: false
    outs:
    - nodes/initialize/MPRester/frames.xyz
    params:
    - initialize_MPRester
  mace_mp_HomonuclearDiatomics:
    cmd: zntrack run mlipx.nodes.diatomics.HomonuclearDiatomics --name mace_mp_HomonuclearDiatomics
    deps:
    - nodes/initialize/MPRester/frames.xyz
    metrics:
    - nodes/mace_mp/HomonuclearDiatomics/node-meta.json:
        cache: false
    outs:
    - nodes/mace_mp/HomonuclearDiatomics/frames.json
    - nodes/mace_mp/HomonuclearDiatomics/results.csv
    params:
    - mace_mp_HomonuclearDiatomics
  orb_v2_HomonuclearDiatomics:
    cmd: zntrack run mlipx.nodes.diatomics.HomonuclearDiatomics --name orb_v2_HomonuclearDiatomics
    deps:
    - nodes/initialize/MPRester/frames.xyz
    metrics:
    - nodes/orb_v2/HomonuclearDiatomics/node-meta.json:
        cache: false
    outs:
    - nodes/orb_v2/HomonuclearDiatomics/frames.json
    - nodes/orb_v2/HomonuclearDiatomics/results.csv
    params:
    - orb_v2_HomonuclearDiatomics
  sevennet_HomonuclearDiatomics:
    cmd: zntrack run mlipx.nodes.diatomics.HomonuclearDiatomics --name sevennet_HomonuclearDiatomics
    deps:
    - nodes/initialize/MPRester/frames.xyz
    metrics:
    - nodes/sevennet/HomonuclearDiatomics/node-meta.json:
        cache: false
    outs:
    - nodes/sevennet/HomonuclearDiatomics/frames.json
    - nodes/sevennet/HomonuclearDiatomics/results.csv
    params:
    - sevennet_HomonuclearDiatomics
